name: esm2_environment

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - biopython
  - tqdm
  - pyyaml
  - matplotlib
  - s3fs
  - boto3

  - pip:
      - fair-esm==2.0.0
      - transformers
      - accelerate
      - datasets
      - sentencepiece
      - safetensors
      - peft
      - protobuf
      - tiktoken
